SiteName: sonada

Save: Save
Play: Play
Stop: Stop

ModulesName: Modules
ModuleName: Module
ModuleConsoleDefault: function gen(t) { return 0.5 * Math.sin(t * 440 * Math.PI * 2); }

WaveName: Wave

SynthaxName: Synthax
SynthaxBuilderName: Builder
SynthaxesName: Synthaxes
SynthaxConsoleDefault: Code <<<function gen(t) { return 0.5 * Math.sin(t * 440 * Math.PI * 2); }>>>
SynthaxBuilderDefault: {"synthax":[{"code":"function gen(t) { return 0.5 * Math.sin(t * 440 * Math.PI * 2); }","type":"code"}]}

UserName: User
