Default: &defaults
  database: sonada.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sonada_test.sqlite3
  <<: *defaults

Staging:
  database: sonada_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: sonada_production.sqlite3
  poolsize: 100
  <<: *defaults
